"""empty message

Revision ID: 9fff722c625d
Revises: e6d9ce623973
Create Date: 2022-07-22 13:32:35.902357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fff722c625d'
down_revision = 'e6d9ce623973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cover_img_url', sa.String(length=255), nullable=True),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('album', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=25), nullable=False),
    sa.Column('artist', sa.String(length=50), nullable=False),
    sa.Column('source', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_songs',
    sa.Column('songs', sa.Integer(), nullable=False),
    sa.Column('playlists', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlists'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['songs'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('songs', 'playlists')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_songs')
    op.drop_table('songs')
    op.drop_table('playlists')
    # ### end Alembic commands ###
