"""empty message

Revision ID: 2fbe783d078d
Revises: 01730a7110a2
Create Date: 2022-07-23 14:41:27.543004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbe783d078d'
down_revision = '01730a7110a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('userId', sa.Integer(), nullable=False))
    op.drop_constraint('songs_user_Id_fkey', 'songs', type_='foreignkey')
    op.create_foreign_key(None, 'songs', 'users', ['userId'], ['id'])
    op.drop_column('songs', 'user_Id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('user_Id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.create_foreign_key('songs_user_Id_fkey', 'songs', 'users', ['user_Id'], ['id'])
    op.drop_column('songs', 'userId')
    # ### end Alembic commands ###
