"""empty message

Revision ID: 0ec99938d404
Revises: 34379ec0ec6d
Create Date: 2022-07-28 14:11:18.749411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec99938d404'
down_revision = '34379ec0ec6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'albumImgUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('albumImgUrl', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
